"use client";

import { Controller, FormProvider, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";
import { useCreateUser } from "@/features/auth/hooks/use-users";
import { useDepartments } from "@/features/departments/hooks/use-departments";
import { JOB_TITLES } from "@/features/auth/constants/staff-options";
import { createUserSchema } from "@/features/auth/validations/create-user.schema";
import type { CreateUserInput } from "@/features/auth/validations/create-user.schema";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  createReceptionistSchema,
  createReceptionistValues,
} from "@/features/receptionists/validations/receptionist.schema";

export default function CreateReceptionistForm() {
  const router = useRouter();
  const createUser = useCreateUser();
  const {
    data: departmentsResponse,
    isPending: isDepartmentsLoading,
    error: departmentsError,
  } = useDepartments();
  const departments = departmentsResponse?.data ?? [];

  const methods = useForm<createReceptionistValues>({
    resolver: zodResolver(createReceptionistSchema),
  });

  const {
    control,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = methods;

  const departmentsUnavailable =
    !departments.length || Boolean(departmentsError);

  const onSubmit = async (values: createReceptionistValues) => {
    try {
      const input = createUserSchema.parse({
        ...values,
        role: "Receptionist",
      } as unknown as CreateUserInput);
      const result = await createUser.mutateAsync(input);
      const receptionistNumber = result.data.receptionistNumber;
      toast.success(
        receptionistNumber
          ? `Receptionist created successfully. Receptionist number: ${receptionistNumber}`
          : "Receptionist created successfully",
      );
      router.push("/admin/receptionists");
    } catch (error) {
      const errorMessage =
        error instanceof Error
          ? error.message
          : "Failed to create receptionist";
      toast.error(errorMessage);
    }
  };

  const renderField = (
    name: keyof createReceptionistValues,
    label: string,
    type: string = "text",
    placeholder: string,
  ) => (
    <div className="space-y-2">
      <Label htmlFor={name}>{label}</Label>
      <Controller
        name={name}
        control={control}
        render={({ field }) => (
          <Input
            {...field}
            value={field.value ?? ""}
            id={name}
            type={type}
            placeholder={placeholder}
            disabled={isSubmitting}
          />
        )}
      />
      {errors[name] && (
        <p className="text-sm text-destructive">{errors[name].message}</p>
      )}
    </div>
  );

  const renderSelect = (
    name: "departmentId" | "jobTitle",
    label: string,
    options: readonly { value: string; label: string }[],
    placeholder: string,
  ) => (
    <div className="space-y-2">
      <Label htmlFor={name}>{label}</Label>
      <Controller
        name={name}
        control={control}
        render={({ field }) => (
          <Select
            onValueChange={field.onChange}
            value={field.value as string | undefined}
            disabled={
              isSubmitting || (name === "departmentId" && isDepartmentsLoading)
            }
          >
            <SelectTrigger id={name}>
              <SelectValue placeholder={placeholder} />
            </SelectTrigger>
            <SelectContent>
              {options.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}
      />
      {errors[name] && (
        <p className="text-sm text-destructive">{errors[name].message}</p>
      )}
    </div>
  );

  const departmentOptions = departments.map((department) => ({
    value: department.id,
    label: department.name,
  }));

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>Add New Receptionist</CardTitle>
          <CardDescription>
            Register a receptionist account. The receptionist number is
            generated by the system. Required fields are marked with
            <span className="text-destructive"> * </span>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <FormProvider {...methods}>
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
              <div className="grid gap-4 sm:grid-cols-2">
                {renderField("name", "Full Name *", "text", "Enter full name")}
                {renderField(
                  "email",
                  "Email *",
                  "email",
                  "Enter email address",
                )}
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                {renderField(
                  "password",
                  "Password *",
                  "password",
                  "Enter password",
                )}
                <div className="space-y-2">
                  <Label htmlFor="role">Role</Label>
                  <Input id="role" value="Receptionist" disabled />
                </div>
              </div>

              <div className="space-y-6 rounded-lg border p-4">
                <p className="text-sm font-medium text-muted-foreground">
                  Staff Details
                </p>
                <div className="grid gap-4 sm:grid-cols-2">
                  {renderSelect(
                    "departmentId",
                    "Department *",
                    departmentOptions,
                    isDepartmentsLoading
                      ? "Loading departments..."
                      : "Select a department",
                  )}
                  {renderField(
                    "employeeCode",
                    "Employee Code *",
                    "text",
                    "Enter employee code",
                  )}
                  {renderSelect(
                    "jobTitle",
                    "Job Title *",
                    JOB_TITLES.map((value) => ({ value, label: value })),
                    "Select a job title",
                  )}
                  {renderField("hireDate", "Hire Date *", "date", "")}
                </div>
                {departmentsError && (
                  <p className="text-sm text-destructive">
                    Unable to load departments. Please try again.
                  </p>
                )}
                {!isDepartmentsLoading &&
                  !departmentsError &&
                  !departments.length && (
                    <p className="text-sm text-destructive">
                      No departments are available. Seed departments before
                      creating receptionists.
                    </p>
                  )}
              </div>

              <div className="flex items-center justify-end gap-3">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => router.push("/admin/receptionists")}
                  disabled={isSubmitting}
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={isSubmitting || departmentsUnavailable}
                >
                  {isSubmitting && (
                    <Loader2 className="mr-2 size-4 animate-spin" />
                  )}
                  Create Receptionist
                </Button>
              </div>
            </form>
          </FormProvider>
        </CardContent>
      </Card>
    </div>
  );
}
