"use client";

import {
  Controller,
  FormProvider,
  useForm,
  type FieldErrors,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";
import { z } from "zod";
import { cn } from "@/lib/utils";
import { useCreatePatientMutation } from "@/features/patients/hooks/use-patients";
import {
  createPatientSchema,
  GENDERS,
} from "@/features/patients/validations/patient.schema";
import type { CreatePatientInput } from "@/features/patients/validations/patient.schema";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const formSchema = createPatientSchema
  .extend({
    confirmPassword: z
      .string({
        error: "Please confirm your password",
      })
      .trim()
      .min(1, {
        error: "Please confirm your password",
      }),
  })
  .superRefine((data, ctx) => {
    if (data.password !== data.confirmPassword) {
      ctx.addIssue({
        code: "custom",
        path: ["confirmPassword"],
        message: "Passwords do not match",
      });
    }
  });

type FormValues = z.infer<typeof formSchema>;

export default function CreatePatientForm() {
  const router = useRouter();
  const createPatient = useCreatePatientMutation();

  const methods = useForm<FormValues>({
    resolver: zodResolver(formSchema),
  });

  const {
    control,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = methods;

  const onSubmit = async (values: FormValues) => {
    try {
      const input: CreatePatientInput = {
        firstName: values.firstName,
        lastName: values.lastName,
        email: values.email,
        password: values.password,
        phn: values.phn,
        phone: values.phone,
        gender: values.gender,
        dateOfBirth: values.dateOfBirth,
        address: values.address,
      };
      const result = await createPatient.mutateAsync(input);
      toast.success("Patient created successfully");
      router.push(`/admin/patients/${result.data.id}`);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to create patient";
      toast.error(errorMessage);
    }
  };

  const onInvalid = (formErrors: FieldErrors<FormValues>) => {
    const firstKey = Object.keys(formErrors)[0] as
      | keyof FormValues
      | undefined;
    if (firstKey) {
      methods.setFocus(firstKey);
    }
  };

  const renderField = (
    name: keyof FormValues,
    label: string,
    type: string = "text",
    placeholder: string,
    className?: string,
  ) => (
    <div className={cn("space-y-2", className)}>
      <Label htmlFor={name}>{label}</Label>
      <Controller
        name={name}
        control={control}
        render={({ field }) => (
          <Input
            {...field}
            value={field.value ?? ""}
            id={name}
            type={type}
            placeholder={placeholder}
            disabled={isSubmitting}
          />
        )}
      />
      {errors[name] && (
        <p className="text-sm text-destructive">{errors[name].message}</p>
      )}
    </div>
  );

  const renderSelect = (
    name: keyof FormValues,
    label: string,
    options: readonly string[],
    placeholder: string,
  ) => (
    <div className="space-y-2">
      <Label htmlFor={name}>{label}</Label>
      <Controller
        name={name}
        control={control}
        render={({ field }) => (
          <Select
            onValueChange={field.onChange}
            value={field.value as string | undefined}
            disabled={isSubmitting}
          >
            <SelectTrigger id={name}>
              <SelectValue placeholder={placeholder} />
            </SelectTrigger>
            <SelectContent>
              {options.map((option) => (
                <SelectItem key={option} value={option}>
                  {option}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}
      />
      {errors[name] && (
        <p className="text-sm text-destructive">{errors[name].message}</p>
      )}
    </div>
  );

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>Add New Patient</CardTitle>
          <CardDescription>
            Register a new patient. The patient number is generated by the
            system. Required fields are marked with
            <span className="text-destructive"> * </span>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <FormProvider {...methods}>
            <form
              onSubmit={handleSubmit(onSubmit, onInvalid)}
              className="space-y-6"
            >
              <div className="space-y-6 rounded-lg border p-4">
                <p className="text-sm font-medium text-muted-foreground">
                  User Information
                </p>
                <div className="grid gap-4 sm:grid-cols-2">
                  {renderField(
                    "firstName",
                    "First Name *",
                    "text",
                    "Enter first name",
                  )}
                  {renderField(
                    "lastName",
                    "Last Name *",
                    "text",
                    "Enter last name",
                  )}
                  {renderField(
                    "email",
                    "Email *",
                    "email",
                    "Enter email address",
                  )}
                  {renderField(
                    "password",
                    "Password *",
                    "password",
                    "Enter password",
                  )}
                  {renderField(
                    "confirmPassword",
                    "Confirm Password *",
                    "password",
                    "Confirm password",
                  )}
                </div>
              </div>

              <div className="space-y-6 rounded-lg border p-4">
                <p className="text-sm font-medium text-muted-foreground">
                  Patient Information
                </p>
                <div className="grid gap-4 sm:grid-cols-2">
                  {renderField("phn", "PHN *", "text", "Enter PHN")}
                  {renderField(
                    "phone",
                    "Phone Number *",
                    "tel",
                    "Enter phone number",
                  )}
                  {renderSelect(
                    "gender",
                    "Gender",
                    GENDERS,
                    "Select gender",
                  )}
                  {renderField(
                    "dateOfBirth",
                    "Date of Birth",
                    "date",
                    "",
                  )}
                  {renderField(
                    "address",
                    "Address *",
                    "text",
                    "Enter address",
                    "sm:col-span-2",
                  )}
                  <div className="space-y-2 sm:col-span-2">
                    <Label htmlFor="patientNumber">Patient Number</Label>
                    <Input
                      id="patientNumber"
                      value="Will be generated automatically"
                      readOnly
                      disabled={isSubmitting}
                    />
                  </div>
                </div>
              </div>

              <div className="flex items-center justify-end gap-3">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => router.push("/admin/patients")}
                  disabled={isSubmitting}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting && (
                    <Loader2 className="mr-2 size-4 animate-spin" />
                  )}
                  Create Patient
                </Button>
              </div>
            </form>
          </FormProvider>
        </CardContent>
      </Card>
    </div>
  );
}
